name: cas-server

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    networks:
      - internal
  

  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cas-router.rule=Host(`api.redio.radhakrishnajewellery.in`)"
      - "traefik.http.services.cas-router.loadbalancer.server.port=80"
      - "traefik.http.routers.cas-router.entrypoints=websecure"
      - "traefik.http.routers.cas-router.tls=true"
      - "traefik.http.routers.cas-router.tls.certresolver=cert-resolver"
      - "traefik.docker.network=cas-network"
    networks:
      - internal
      - cas-network

networks:
  internal:
    driver: bridge
  cas-network:
    external: true