name: traefik

services:
  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    environment:
      - DOCKER_API_VERSION=1.53
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.cert-resolver.acme.httpchallenge=true
      - --certificatesresolvers.cert-resolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.cert-resolver.acme.email=shivangtripathi101@gmail.com
      - --certificatesresolvers.cert-resolver.acme.storage=/letsencrypt/acme.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certificates:/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - cas-network

networks:
  cas-network:
    name: cas-network
    driver: bridge