version: "3.9"

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cas-router.rule=Host(`api.redio.radhakrishnajewellery.in`)"
      - "traefik.http.routers.cas-router.entrypoints=websecure"
      - "traefik.http.routers.cas-router.tls.certresolver=cert-resolver"
      - "traefik.http.services.cas-service.loadbalancer.server.port=3000"
      - "traefik.docker.network=cas-network"
    networks:
      - internal
      - cas-network

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_DATABASE: cloud_audio_scheduler
      MYSQL_USER: cas_user
      MYSQL_PASSWORD: dbpass
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - internal

volumes:
  db_data:

networks:
  internal:
    driver: bridge
  cas-network:
    external: true